[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[edge_functions]]
  function = "generate"
  path = "/api/generate"

[[redirects]]
  from = "/api/commit"
  to = "/.netlify/functions/commit"
  status = 200

[[redirects]]
  from = "/api/voting/*"
  to = "/.netlify/functions/voting/:splat"
  status = 200

[dev]
  framework = "#static"
